### ISSUE TITLE
No conversion if dff2dsf.exe is in same directory at dff2dsfTool

### ISSUE THREAD

**Issue by sveakul** [Nokama0/dff2dsfTool#1]
With dff2dsfTool.exe in its own folder, if dff2dsf.exe is also placed in that folder or a subdirectory thereof, while path can be selected in the GUI, no file conversion actually happens despite appearing so in the log window--no file appears in the chosen destination folder.

Moving dff2dsf.exe to its own folder and reselecting the path in dff2dsfTool results in a converted file in the destination folder.

**Comment by sveakul** [comment]
Edit:  Am using latest versions of both files from Signalyst and this site.  OS is Windows 10 x64 22H2.

**Comment by Jigglyy** [comment]
I have the same issue, Win 11 x64 22H2.

**Comment by Sturdzza** [comment]
works fine for me on ubuntu with wine

**Comment by Jigglyy** [comment]
Why did you delete the comments? They were genuine questions, I also found it interesting that the same issue somehow got replicated on wine from Sturdza, can you give the steps on how you replicated it with Wine?

**Comment by xkYzzo** [comment]
Salut, am si eu problema asta pe Windows 10 versiunea 22H2

**Comment by Nokama0** [comment]
I added better error reading so the tool should now properly output Signalyst's tool errors in the LogBox. It is worth noting that Signalyst's tool doesn't work with compressed DFF files.
I also tested it with both this executables in the same folder and it works correctly.

I added a new release which contains all these changes.

**Comment by sveakul** [comment]
Thank you, works perfectly now!  I appreciate the fix.
